name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      MONGO_WAIT_TIMEOUT: 60
      ES_WAIT_TIMEOUT: 180
      KAFKA_FLUSH_TIMEOUT: 10
      CONSUMER_SHUTDOWN_TIMEOUT: 10
      KAFKA_TEST_TOPIC: reviews
      NUM_TEST_MESSAGES: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential librdkafka-dev libsasl2-dev libssl-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --max-line-length=120
        continue-on-error: true

      - name: Check formatting with black
        run: |
          pip install black
          black --check .
        continue-on-error: true

      - name: Security scan with bandit
        run: |
          pip install bandit
          bandit -r app/ -ll
        continue-on-error: true

      - name: Dependency vulnerability scan
        run: |
          pip install pip-audit
          pip-audit
        continue-on-error: true

      - name: Fix Docker socket perms (needed by testcontainers)
        run: sudo chmod 666 /var/run/docker.sock || true

      - name: Run integration tests
        run: pytest -v -m integration